/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageUserRouteImport } from './routes/manage/user'
import { Route as ManageModuleRouteImport } from './routes/manage/module'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUserRoute = ManageUserRouteImport.update({
  id: '/manage/user',
  path: '/manage/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageModuleRoute = ManageModuleRouteImport.update({
  id: '/manage/module',
  path: '/manage/module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/manage/module': typeof ManageModuleRoute
  '/manage/user': typeof ManageUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/manage/module': typeof ManageModuleRoute
  '/manage/user': typeof ManageUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/manage/module': typeof ManageModuleRoute
  '/manage/user': typeof ManageUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/login' | '/manage/module' | '/manage/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/login' | '/manage/module' | '/manage/user'
  id: '__root__' | '/' | '/about' | '/login' | '/manage/module' | '/manage/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ManageModuleRoute: typeof ManageModuleRoute
  ManageUserRoute: typeof ManageUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/user': {
      id: '/manage/user'
      path: '/manage/user'
      fullPath: '/manage/user'
      preLoaderRoute: typeof ManageUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/module': {
      id: '/manage/module'
      path: '/manage/module'
      fullPath: '/manage/module'
      preLoaderRoute: typeof ManageModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ManageModuleRoute: ManageModuleRoute,
  ManageUserRoute: ManageUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
