/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserAccountRouteImport } from './routes/user/$account'
import { Route as ManageUserRouteImport } from './routes/manage/user'
import { Route as ManageModuleRouteImport } from './routes/manage/module'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAccountRoute = UserAccountRouteImport.update({
  id: '/user/$account',
  path: '/user/$account',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUserRoute = ManageUserRouteImport.update({
  id: '/manage/user',
  path: '/manage/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageModuleRoute = ManageModuleRouteImport.update({
  id: '/manage/module',
  path: '/manage/module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/manage/module': typeof ManageModuleRoute
  '/manage/user': typeof ManageUserRoute
  '/user/$account': typeof UserAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/manage/module': typeof ManageModuleRoute
  '/manage/user': typeof ManageUserRoute
  '/user/$account': typeof UserAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/manage/module': typeof ManageModuleRoute
  '/manage/user': typeof ManageUserRoute
  '/user/$account': typeof UserAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/login'
    | '/unauthorized'
    | '/manage/module'
    | '/manage/user'
    | '/user/$account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/login'
    | '/unauthorized'
    | '/manage/module'
    | '/manage/user'
    | '/user/$account'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/login'
    | '/unauthorized'
    | '/manage/module'
    | '/manage/user'
    | '/user/$account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ManageModuleRoute: typeof ManageModuleRoute
  ManageUserRoute: typeof ManageUserRoute
  UserAccountRoute: typeof UserAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$account': {
      id: '/user/$account'
      path: '/user/$account'
      fullPath: '/user/$account'
      preLoaderRoute: typeof UserAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/user': {
      id: '/manage/user'
      path: '/manage/user'
      fullPath: '/manage/user'
      preLoaderRoute: typeof ManageUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/module': {
      id: '/manage/module'
      path: '/manage/module'
      fullPath: '/manage/module'
      preLoaderRoute: typeof ManageModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ManageModuleRoute: ManageModuleRoute,
  ManageUserRoute: ManageUserRoute,
  UserAccountRoute: UserAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
